### ISSUE TITLE
Alter file save location

### ISSUE THREAD

**Issue by zyme-xd** [StarburstAudio/loopbase#32]
**Is your feature request related to a problem? Please describe.**
I think its kinda annoying to have to go the C drive , go to users, etc just to get my loop. 

**Describe the solution you'd like**
Maybe you can implement a settings menu where you can customize the save location, and have an option so it opens the folder the file is contained in automatically

**Describe alternatives you've considered**
Maybe making a quick short cut on my desktop

**Comment by stxarixdust** [comment]
Closed as a duplicate of #28 and #25.
