### ISSUE TITLE
Drag and drop loops like splice?

### ISSUE THREAD

**Issue by zyme-xd** [StarburstAudio/loopbase#33]
**Is your feature request related to a problem? Please describe.**
Having the ability to drag and drop loops directly into my DAW would be nice, just like splice

**Describe the solution you'd like**
Maybe make it so you click and drag the sample into your DAW

**Describe alternatives you've considered**
Manually going to my samples folder and dragging and dropping from there...

**Comment by stxarixdust** [comment]
Hey, this is already possible :) If you download a loop, you should see it turn green, and the download icon will be replaced with a draggable one (this one down here)!

![](https://user-images.githubusercontent.com/68156346/147784611-bea24f27-ca29-4787-99ca-de59b5bb9525.png)

In the redesign (#31), this feature will be made more apparent (i.e. the entire loop will be draggable)

**Comment by zyme-xd** [comment]
Ah okay thank you!

**Comment by stxarixdust** [comment]
No problem!
